name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Astro site
      - name: Build site
        run: npm run build

      # Prettier formatting check
      - name: Prettier check
        run: npx prettier --write "**/*.{js,ts,astro,css,html,json,md}" 

      # ESLint check
      - name: ESLint check
        run: npx eslint . --ext .js,.ts,.astro

      # TypeScript type check
      - name: TypeScript check
        run: npx tsc --noEmit

      # Accessibility check with Pa11y
      - name: Accessibility check
        run: |
          if compgen -G "dist/*.html" > /dev/null; then
            for file in dist/*.html; do
              echo "Running Pa11y on $file"
              npx pa11y "file://$PWD/$file" --config pa11y.config.cjs
            done
          else
            echo "No HTML files found in dist/, skipping Pa11y."
          fi
      
      # Allow Deploy job to be able to have access to files
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-assets
          path: ./dist

  deployment:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      # Access files from the upload build artifact step in build-and-test job
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: production-assets
          path: ./dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # --delete removes old files in s3 that are not present in the new build
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET }} --delete

      # Ensures users see the newest project version immediately upon deployment
      - name: Invalidate Cloudfront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/"
